version: "3.6"

services:

   front-client:   
      build:
         context: ./frontend
         dockerfile: Dockerfile
      restart: always
      ports:
         - 1488:3000
      environment: 
         - REACT_APP_API_URL=https://vireal.defernus.com
      volumes: 
         - ./frontend:/app

   backend:   
      build:
         context: ./backend
         dockerfile: Dockerfile
      restart: always
      ports:
         - 5000:5000
      volumes: 
         - ./backend:/app